-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║ 0001_init — authoring domain (Этап 1)                                      ║
-- ║ Task bank · trainers · courses/intensives · lessons · widgets             ║
-- ║                                                                            ║
-- ║ Design notes:                                                              ║
-- ║  • Scalar, filterable fields (subject/section/topic/part/line/source/      ║
-- ║    difficulty/answer_type) are real columns → fast WHERE + indexes.        ║
-- ║  • Rich nested config (table, choices, keys, criteria, match cols…) is     ║
-- ║    jsonb, mirroring the frontend Task shape 1:1 so mapping is trivial.     ║
-- ║  • RLS is ON everywhere. For now: read = public, write = authenticated.    ║
-- ║    Этап 3 tightens writes to teacher-role (profiles.role).                 ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- gen_random_uuid()
create extension if not exists pgcrypto;

-- Auto-maintain updated_at on any table that has the column.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── Task bank ─────────────────────────────────────────────────────────────────
-- The numbered question bank. `id` IS the "номер" teachers see (№315, №1401…).
-- `by default as identity` lets us seed explicit historical ids yet auto-number
-- new ones.
create table public.task_bank (
  id          bigint generated by default as identity primary key,
  subject     text   not null,                       -- 'biology' | 'chemistry' | …
  section     text   not null default '',
  topic       text   not null default '',
  part        smallint not null default 1 check (part in (1, 2)),
  line        int    not null default 1,
  source      text   not null default '',
  question    text   not null default '',
  answer      text   not null default '',
  solution    text   not null default '',
  difficulty  text   not null default 'medium' check (difficulty in ('easy','medium','hard')),

  question_table jsonb,                               -- { headers:[], rows:[[]] }
  question_image text,                                -- Storage URL

  -- scoring
  question_type text check (question_type in ('choice','free')),
  score_mode    text check (score_mode in ('perOption','criteria','whole')),
  choices       jsonb,                                -- [{id,text,correct,points}]
  answer_keys   jsonb,                                -- [{id,keyword,points}]
  criteria      jsonb,                                -- [{id,text,points}]
  criteria_visible_on_check boolean not null default false,
  max_points    int not null default 1,

  -- rich answer block
  answer_type    text check (answer_type in ('single','multi','short','matching','sequence','tableFill','extended')),
  match_left     jsonb,                               -- string[]
  match_right    jsonb,                               -- string[]
  sequence_items jsonb,                               -- string[]
  allow_photo    boolean not null default false,

  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index task_bank_subject_idx    on public.task_bank (subject);
create index task_bank_section_idx    on public.task_bank (section);
create index task_bank_topic_idx      on public.task_bank (topic);
create index task_bank_part_line_idx  on public.task_bank (part, line);
create index task_bank_source_idx     on public.task_bank (source);
create index task_bank_difficulty_idx on public.task_bank (difficulty);
-- full-text-ish search on question text (trigram) — optional but handy:
create extension if not exists pg_trgm;
create index task_bank_question_trgm  on public.task_bank using gin (question gin_trgm_ops);
create trigger task_bank_set_updated_at before update on public.task_bank
  for each row execute function public.set_updated_at();

-- ── Trainers ──────────────────────────────────────────────────────────────────
create table public.trainers (
  id          uuid primary key default gen_random_uuid(),
  title       text not null default '',
  topic       text not null default '',
  subject     text not null default '',
  difficulty  text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  time_per_question int not null default 2,
  color       text not null default '#9B6DFF',
  bg          text not null default '#E4D9FF',
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger trainers_set_updated_at before update on public.trainers
  for each row execute function public.set_updated_at();

-- A trainer is an ordered set of bank questions (Trainer.questionIds).
create table public.trainer_questions (
  trainer_id  uuid   not null references public.trainers(id) on delete cascade,
  task_id     bigint not null references public.task_bank(id) on delete cascade,
  position    int    not null default 0,
  primary key (trainer_id, task_id)
);
create index trainer_questions_trainer_idx on public.trainer_questions (trainer_id, position);

-- ── Courses & intensives ──────────────────────────────────────────────────────
-- `kind` distinguishes a full course from a short intensive (интенсив).
create table public.courses (
  id          uuid primary key default gen_random_uuid(),
  kind        text not null default 'course' check (kind in ('course','intensive')),
  title       text not null default '',
  subject     text not null default '',
  level       text not null default '',
  description text not null default '',
  status      text not null default 'draft' check (status in ('draft','published')),
  color       text not null default '#B98FFF',
  bg          text not null default '#EFE0FF',
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index courses_kind_idx   on public.courses (kind);
create index courses_status_idx on public.courses (status);
create trigger courses_set_updated_at before update on public.courses
  for each row execute function public.set_updated_at();

-- ── Widgets ───────────────────────────────────────────────────────────────────
create table public.widgets (
  id          uuid primary key default gen_random_uuid(),
  title       text not null default '',
  type        text not null default 'quiz',
  linked_trainer_id uuid references public.trainers(id) on delete set null,
  items       jsonb not null default '[]'::jsonb,
  color       text not null default '#7B3FCC',
  bg          text not null default '#EEDBFF',
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger widgets_set_updated_at before update on public.widgets
  for each row execute function public.set_updated_at();

-- ── Lessons (belong to a course, ordered) ─────────────────────────────────────
create table public.lessons (
  id          uuid primary key default gen_random_uuid(),
  course_id   uuid not null references public.courses(id) on delete cascade,
  title       text not null default '',
  position    int  not null default 0,
  trainer_id  uuid references public.trainers(id) on delete set null,
  widget_id   uuid references public.widgets(id)  on delete set null,
  youtube_url text,
  description text,
  materials   jsonb not null default '[]'::jsonb,   -- uploaded files (Storage URLs)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index lessons_course_idx on public.lessons (course_id, position);
create trigger lessons_set_updated_at before update on public.lessons
  for each row execute function public.set_updated_at();

-- ── Row Level Security ────────────────────────────────────────────────────────
-- Content is readable by anyone (students browse it). Writes require a logged-in
-- user for now; Этап 3 narrows writes to teachers via a profiles.role check.
do $$
declare t text;
begin
  foreach t in array array[
    'task_bank','trainers','trainer_questions','courses','widgets','lessons'
  ] loop
    execute format('alter table public.%I enable row level security;', t);
    execute format($p$create policy "read_all_%1$s" on public.%1$I for select using (true);$p$, t);
    execute format($p$create policy "write_auth_%1$s" on public.%1$I for all to authenticated using (true) with check (true);$p$, t);
  end loop;
end $$;
